services:
  - type: web
    name: stylo-web
    env: node
    plan: free
    buildCommand: |
      npm install
      cd client && npm install && npm run build && cd ..
    startCommand: node server/index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        # Set this to your Render custom domain later if you add one
        fromService: stylo-web
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

